Added card component and style
Hend001/Brick-project pull request #13
Opened 2023-11-25 22:08 UTC by Pushpa88431

sync dev to card_component

2023-11-25 22:09 UTC, Pushpa88431 commented
Merged

2023-11-27 10:04 UTC, JerryUusis commented
I'll review this today

2023-11-27 13:42 UTC, JerryUusis commented on frontend/src/App.css
> +  color: brown;
Brown isn't on the color palette that's been defined at the first row of the CSS file.

2023-11-27 14:13 UTC, JerryUusis requested changes
The branch feature is supposed to be Card component so I was expeceting a Card component and a few selectors in CSS. Now there's closer to 60 lines of code added to CSS.

There is quite a chunk of unused code here. Let's not push unused code on the dev/main branches. Consider refactoring the changes made in to App.css instead of trying to fix them one by one.

2023-11-27 14:13 UTC, JerryUusis commented on frontend/src/App.css
> +.card .content {
This class isn't used anywhere

2023-11-27 14:13 UTC, JerryUusis commented on frontend/src/App.css
> +  background-color: rgb(3, 60, 9);
This color isn't from the color palette. Please use CSS variable `--hunter-green`.

2023-11-27 14:13 UTC, JerryUusis commented on frontend/src/App.css
> +  width: 300px;
Using relative units for child elements is a better way to make sure they are right size. For example here `width: 100%` will work better.

2023-11-27 14:13 UTC, JerryUusis commented on frontend/src/App.css
> +  margin: 0;
There isn't a h2 element on the card. `margin: 0` has been declared with the universal selector on line 18.

2023-11-28 05:19 UTC, closed without merging